In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
df = pd.read_csv('/content/movies_metadata.csv')

In [ ]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
df.columnsd

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
df.shape

(45466, 24)

In [ ]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(13)

In [ ]:
df = df.drop_duplicates().reset_index(drop=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df[['genres','title','vote_average','vote_count','tagline','popularity','overview']]

In [ ]:
df

,genres,title,vote_average,vote_count,tagline,popularity,overview
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",Toy Story,7.7,5415.0,NaN,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Jumanji,6.9,2413.0,Roll the dice and unleash the excitement!,17.015539,When siblings Judy and Peter discover an encha...
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Grumpier Old Men,6.5,92.0,Still Yelling. Still Fighting. Still Ready for...,11.7129,A family wedding reignites the ancient feud be...
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Waiting to Exhale,6.1,34.0,Friends are the people who let you be yourself...,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,"[{'id': 35, 'name': 'Comedy'}]",Father of the Bride Part II,5.7,173.0,Just When His World Is Back To Normal... He's ...,8.387519,Just when George Banks has recovered from his ...
...,...,...,...,...,...,...,...
45448,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Subdue,4.0,1.0,Rising and falling between a man and woman,0.072051,Rising and falling between a man and woman.
45449,"[{'id': 18, 'name': 'Drama'}]",Century of Birthing,9.0,3.0,NaN,0.178241,An artist struggles to finish his work while a...
45450,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Betrayal,3.8,6.0,A deadly game of wits.,0.903007,"When one of her hits goes wrong, a professiona..."
45451,[],Satan Triumphant,0.0,0.0,NaN,0.003503,"In a small town live two brothers, one a minis..."
45452,[],Queerama,0.0,0.0,NaN,0.163015,50 years after decriminalisation of homosexual...

In [ ]:
df.isnull().sum()

genres              0
title               6
vote_average        6
vote_count          6
tagline         25045
popularity          5
overview          954
dtype: int64

In [ ]:
df = df.dropna(subset=['title'])

In [ ]:
df['overview'] = df['overview'].fillna('')

In [ ]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [ ]:
import ast
df['genres'] = df['genres'].apply(lambda x:" ".join([i['name'] for i in ast.literal_eval(x)]) )

Step 1: Import the ast module
import ast

The ast module provides the function literal_eval() which safely converts a string that looks like a Python object (like a list or dictionary) into an actual Python object.

Example:

"[{'id': 28, 'name': 'Action'}]"

becomes

[{'id': 28, 'name': 'Action'}]
Step 2: Apply a function to the genres column
df['genres'].apply(...)

The apply() function runs a given function on each row of the column.

Step 3: Use a lambda function
lambda x:

A lambda function is a small anonymous function.
Here, x represents each value in the genres column.

Example value of x:

"[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}]"
Step 4: Convert string to Python list
ast.literal_eval(x)

This converts the string into a Python list of dictionaries.

Example result:

[
 {'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'}
]
Step 5: Extract genre names
[i['name'] for i in ast.literal_eval(x)]

This is list comprehension. It loops through each dictionary and extracts the name value.

Result:

['Action', 'Adventure']
Step 6: Join the names into one string
" ".join(...)

The join() function combines the list into a single string separated by spaces.

Result:

"Action Adventure"

In [ ]:
df.head()

,genres,title,vote_average,vote_count,tagline,popularity,overview
0,Animation Comedy Family,Toy Story,7.7,5415.0,NaN,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Adventure Fantasy Family,Jumanji,6.9,2413.0,Roll the dice and unleash the excitement!,17.015539,When siblings Judy and Peter discover an encha...
2,Romance Comedy,Grumpier Old Men,6.5,92.0,Still Yelling. Still Fighting. Still Ready for...,11.7129,A family wedding reignites the ancient feud be...
3,Comedy Drama Romance,Waiting to Exhale,6.1,34.0,Friends are the people who let you be yourself...,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Comedy,Father of the Bride Part II,5.7,173.0,Just When His World Is Back To Normal... He's ...,8.387519,Just when George Banks has recovered from his ...

In [ ]:
df['tagline'] = df['tagline'].fillna('')

In [ ]:
df.isnull().sum()

genres          0
title           0
vote_average    0
vote_count      0
tagline         0
popularity      0
overview        0
dtype: int64

In [ ]:
df = df[['title','genres','tagline','overview','popularity','vote_average']]

In [ ]:
df.isnull().sum()

title           0
genres          0
tagline         0
overview        0
popularity      0
vote_average    0
dtype: int64

In [ ]:
df['tags'] = df['genres'] + " " + df['overview'] + " " + df['tagline']

In [ ]:
df.head()

,title,genres,tagline,overview,popularity,vote_average,tags
0,Toy Story,Animation Comedy Family,,"Led by Woody, Andy's toys live happily in his ...",21.946943,7.7,"Animation Comedy Family Led by Woody, Andy's t..."
1,Jumanji,Adventure Fantasy Family,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,17.015539,6.9,Adventure Fantasy Family When siblings Judy an...
2,Grumpier Old Men,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,11.7129,6.5,Romance Comedy A family wedding reignites the ...
3,Waiting to Exhale,Comedy Drama Romance,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...",3.859495,6.1,"Comedy Drama Romance Cheated on, mistreated an..."
4,Father of the Bride Part II,Comedy,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,8.387519,5.7,Comedy Just when George Banks has recovered fr...

In [ ]:
df['tags'][0]

"Animation Comedy Family Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. "

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [ ]:
def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #remove the punctuations
  text = re.sub('[^a-zA-Z]', ' ', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]
  #lemitization
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [ ]:
df['tags'] = df['tags'].apply(preprocess_text)

In [ ]:
df['tags'][0]

'animation comedy family led woody andy toy live happily room andy birthday brings buzz lightyear onto scene afraid losing place andy heart woody plot buzz circumstance separate buzz woody owner duo eventually learns put aside difference'

In [ ]:
df = df.reset_index(drop= True)

In [ ]:
indices = pd.Series(df.index, index=df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [ ]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [ ]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1582174 stored elements and shape (45447, 50000)>

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[ : :-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [ ]:
recommend('Avatar')

26547                                      Avatar 2
13883                          The Inhabited Island
26553                                Thor: Ragnarok
6414     Lara Croft Tomb Raider: The Cradle of Life
14119                          The Three Musketeers
28403                        France société anonyme
43983                           Nightmare City 2035
20372                                        Désiré
2457                                     The Matrix
16331                           On the Silver Globe
Name: title, dtype: object

In [ ]:
import pickle

In [ ]:
pickle.dump(df,open('movies.pkl','wb'))

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

pickle.dump(tfidf,open('tfidf.pkl','wb'))